Added data for EO 1-100
wolfcomp/DeepDungeonDex pull request #125
Opened 2023-04-12 01:37 UTC by Claided

Edited and Added Mob data for EO 1-50. Added Mob data and EN localization for EO 51-100. Updated EO 1-100 Floor data with info I find useful. Mob Data based on personal experience, Maygi's guide, and Meifa's EO QuickRef spreadsheet. 
First time doing a pull request, so I hope it helps!

2023-04-12 17:27 UTC, wolfcomp commented
Please redo your pr to use the newest data commits as these have conflicts

2023-04-13 19:16 UTC, Claided commented
Sorry about that, I didn't see your latest commits. I think the conflicts have been resolved and it should be able to be merged.

2023-04-14 02:54 UTC, wolfcomp requested changes
Still not fully done with what is done with the file for what is on the main data branch

2023-04-14 02:54 UTC, wolfcomp commented on EO/51-100.yml
Would gladly take that you redo this file completely to what is done in the main data branch

2023-04-14 02:54 UTC, wolfcomp commented on Localization/en/EO/51-100.yml
This file is not properly formatted and needs to be looked at since it still contains merge conflict parts

2023-04-26 12:56 UTC, closed without merging